### ISSUE TITLE
Start process when the radar is not running. process exit directly

### ISSUE THREAD

**Issue by zjyspp** [SICKAG/sick_safetyscanners2#24]
the process startup when the radar is not running, it will exit directly。
[sick_safetyscanners2_node-1] terminate called after throwing an instance of 'sick::runtime_error'
[sick_safetyscanners2_node-1]   what():  No route to host

**Comment by Raymond601** [comment]
Hi @puck-fzi 
is there any experience of this situation we met?
thank you very much!

**Comment by puck-fzi** [comment]
Dear all,
since your radar is not running, yes the driver will exit with the experienced error. This driver needs a running instance of the sensor to communicate to. 
Currently there is no reconnect or multiple connecting tries implemented in the driver. Therefore, if no connection to the hardware is found the driver will exit.
